### ISSUE TITLE
Initialize arguments with valid values

### ISSUE THREAD

**Issue by DevikaJaladi** [rdkcentral/rdkv-halif-test-wifi#11]
1. Initializing Input/Output arguments of wifi-hall APIs with valid values before calling actual API.
2. Removing "l1_wifi_common_hal_negative4_wifi_getRegulatoryDomain" as it doesn't matter what is passed to wifi_getRegulatoryDomain() in the output_string argument provided it is long enough to store the regulatory domain string.
3. Below TCs(Input buffer size issue) are commented out 
    test_l1_wifi_common_hal_negative4_wifi_getRadioSupportedFrequencyBands
    test_l1_wifi_common_hal_negative4_wifi_getRadioChannelsInUse
    test_l1_wifi_common_hal_negative4_wifi_getRadioPossibleChannels

**Comment by hari22yuva** [comment]
code is merged to develop
