### ISSUE TITLE
Fixing positive1/positive2 wifi_lastConnected_Endpoint() TC failure

### ISSUE THREAD

**Issue by DevikaJaladi** [rdkcentral/rdkv-halif-test-wifi#13]
Fixing the below Tc failures:
1. test_l1_wifi_client_hal_positive1_wifi_lastConnected_Endpoint()
2. test_l1_wifi_client_hal_positive2_wifi_lastConnected_Endpoint()

**Comment by hari22yuva** [comment]
merged to develop
