### ISSUE TITLE
Fixing postive and negative TCs of test_L1_wifi_common_hal and test_L1_wifi_client_hal 

### ISSUE THREAD

**Issue by DevikaJaladi** [rdkcentral/rdkv-halif-test-wifi#15]
Fixing the below Tc failures:
1. test_l1_wifi_common_hal_negative3_wifi_getSpecificSSIDInfo
2. test_l1_wifi_common_hal_negative3_wifi_getNeighboringWiFiDiagnosticResult

Commenting out invalid radioIndex/ssidIndex TCs for now.
1. test_l1_wifi_common_hal_negative2_wifi_getRadioTransmitPowerSupported
2. test_l1_wifi_common_hal_negative1_wifi_getRadioTransmitPower
3. test_l1_wifi_common_hal_negative1_wifi_getRadioSupportedStandards 
4. test_l1_wifi_client_hal_negative1_wifi_setCliWpsEnrolleePin
5. test_l1_wifi_common_hal_negative1_wifi_getRadioSupportedStandards

**Comment by DevikaJaladi** [comment]
Fixing below TCs as well:
1. test_l1_wifi_client_hal_positive2_wifi_getRoamingControl
2. test_l1_wifi_client_hal_negative11_wifi_connectEndpoint
3. test_l1_wifi_client_hal_negative1_wifi_cancelWpsPairing

**Comment by hari22yuva** [comment]
merged to develop
