### ISSUE TITLE
Fixing Positive1 TC of wifi_getRoamingControl()

### ISSUE THREAD

**Issue by Anand73-n** [rdkcentral/rdkv-halif-test-wifi#17]
Fixing below TC failure
1. test_l1_wifi_client_hal_positive1_wifi_getRoamingControl

Below negative TCs are commented out because the parameters used are not required to check.
1. test_l1_wifi_client_hal_negative1_wifi_disconnectEndpoint
2. test_l1_wifi_client_hal_negative2_wifi_disconnectEndpoint
3. test_l1_wifi_client_hal_negative3_wifi_connectEndpoint

**Comment by hari22yuva** [comment]
merged to develop
