### ISSUE TITLE
Fixing TCs of wifi_getNeighboringWiFiDiagnosticResult

### ISSUE THREAD

**Issue by DevikaJaladi** [rdkcentral/rdkv-halif-test-wifi#20]
Fixing below TCs

test_l1_wifi_common_hal_positive1_wifi_getNeighboringWiFiDiagnosticResult
test_l1_wifi_common_hal_negative2_wifi_getNeighboringWiFiDiagnosticResult

**Comment by hari22yuva** [comment]
merged to develop
