### ISSUE TITLE
Fix l1_wifi_common_hal positive and negative TCs

### ISSUE THREAD

**Issue by Anand73-n** [rdkcentral/rdkv-halif-test-wifi#24]
Fixing below TCs failure
    1. test_l1_wifi_common_hal_positive1_wifi_getRadioPossibleChannels
    2. test_l1_wifi_common_hal_positive1_getStats
    3. test_l1_wifi_common_hal_negative2_wifi_initWithConfig
    4. test_l1_wifi_common_hal_negative3_wifi_initWithConfig
    
    Below TCs are commented out as invalid ssid index are not handled in current wifi hal.
    1. test_l1_wifi_common_hal_negative3_wifi_setRadioScanningFreqList

**Comment by hari22yuva** [comment]
merged to develop
