### ISSUE TITLE
Fixing L1 wifi_client_hal post-init tests

### ISSUE THREAD

**Issue by Anand73-n** [rdkcentral/rdkv-halif-test-wifi#26]
Fixing below TCs
1. test_l1_wifi_client_hal_positive1_wifi_getCliWpsConfigMethodsEnabled
2. test_l1_wifi_client_hal_positive2_wifi_getCliWpsConfigMethodsEnabled
3. test_l1_wifi_common_hal_positive1_wifi_getRadioStandard

Below TC is commented out for now because invalid freq. list are currently not handled in the wifi-hal API.
1. test_l1_wifi_common_hal_negative2_wifi_setRadioScanningFreqList

Below TC is commented out, because invalid ssidIndex values are not handled in wifi-hal.
1. test_l1_wifi_client_hal_negative1_wifi_setCliWpsEnrolleePin

Below TCs are moved to post_connect_tests
1. test_l1_wifi_common_hal_positive1_wifi_getRadioStandard
2. test_l1_wifi_common_hal_positive1_wifi_getRadioChannel
3. test_l1_wifi_common_hal_positive1_wifi_getSpecificSSIDInfo

**Comment by hari22yuva** [comment]
merged to develop
