### ISSUE TITLE
Including wifi connect mechanism as precondition for listed APIs

### ISSUE THREAD

**Issue by DevikaJaladi** [rdkcentral/rdkv-halif-test-wifi#8]
Adding new test suite it will be with below list of APIs where wifi connect mechanism included as pre-condition
1.    test_l1_wifi_common_hal_positive1_wifi_getSSIDName
2.    test_l1_wifi_common_hal_boundary1_wifi_getSSIDName
3.    test_l1_wifi_common_hal_positive1_wifi_getBaseBSSID
4.    test_l1_wifi_common_hal_positive1_wifi_getSSIDMACAddress
5.    test_l1_wifi_common_hal_positive1_getStats
6.    test_l1_wifi_common_hal_positive1_wifi_getRadioOperatingChannelBandwidth
7.    test_l1_wifi_common_hal_positive1_wifi_getRadioMCS
8.    test_l1_wifi_common_hal_positive1_wifi_getRadioTransmitPower
9.    test_l1_wifi_common_hal_positive1_wifi_getRadioTrafficStats

**Comment by hari22yuva** [comment]
Code is merged to develop
